package lt.techin.karolina.sablonai.patterns.problem;

public class MainForTest {
    public static void main(String[] args) {
        Cow cow = new Cow();
        cow.makeSound(); // print Animal make sound ...
        cow.run(); // print Cow is run ...
        Duck duck = new Duck();
        duck.makeSound(); // print Animal make sound ...
        duck.run(); // print Duck is run ...
    }
}
